### ISSUE TITLE
Polar cloud error

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/OctoPrint-PolarCloud#2]
```
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:04:12,859 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:04:12,865 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 1.85777075584 seconds
2018-03-15 17:04:38,021 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:04:38,193 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:04:39,625 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.82938829982 seconds
2018-03-15 17:05:21,066 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:05:21,159 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:06:17,423 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 1.85489159673 seconds
2018-03-15 17:07:24,692 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:07:56,826 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:08:19,476 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.15717637724 seconds
2018-03-15 17:10:18,127 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:11:34,722 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:12:39,594 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 1.72887687861 seconds
2018-03-15 17:25:27,335 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:26:04,723 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:26:24,605 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.52125510207 seconds
2018-03-15 17:27:03,357 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:28:44,876 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:29:30,953 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.40306857821 seconds
2018-03-15 17:32:22,702 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:34:36,895 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:34:36,919 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.24076052039 seconds
2018-03-15 17:37:52,904 - octoprint.plugins.polarcloud - ERROR - Unable to open socket ConnectionError: '('Connection aborted.', gaierror(-2, 'Name or service not known'))' @ __init__.py:_create_socket:255
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_polarcloud/__init__.py", line 255, in _create_socket
    self._socket = SocketIO(self._settings.get(['service']), Namespace=LoggingNamespace, verify=True, wait_for_connection=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 82, in recv_packet
    **self._kw_get)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/socketIO_client/transports.py", line 180, in get_response
    raise ConnectionError(e)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
2018-03-15 17:38:10,604 - octoprint.plugins.polarcloud - INFO - Socket created.
2018-03-15 17:38:34,141 - octoprint.plugins.polarcloud - WARNING - unable to create socket to Polar Cloud, check again in 2.19022234054 seconds
``

**Comment by Ximidar** [comment]
This happened on fantastic-rodenberry. Upon further analysis I found that the python executable had been corrupted which prevented the entire octoprint system from starting up. It's important to note that these two incidents may have nothing to do with eachother. 

@jerryrobo3d Had Re-Made fantastic rodenberry and will be re-installing polar cloud to see if the error can cause problems.

**Comment by AllenMcAfee** [comment]
@jerryrobo3d @Ximidar any update on this reinstall?

**Comment by Ximidar** [comment]
@AllenMcAfee I installed polar cloud onto Jerry's machine. It's just a waiting game, I believe this error is due to the printer not having an internet connection, so it would continually try to reconnect. I'll make sure his printer is set up with his polar cloud account so we can start testing.

**Comment by AllenMcAfee** [comment]
Seems to be fixed with the latest updates to the dependency installs.
